FROM openjdk:17-jdk-alpine
ADD target/standard-reduced-rates-service-0.0.1-SNAPSHOT.jar standard-reduced-rates-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["sh", "-c", "java -jar /standard-reduced-rates-service-0.0.1-SNAPSHOT.jar"]